In [1]:
import numpy as np
import pandas as pd

In [2]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [3]:
df=pd.read_csv(r"C:\Users\tyagi\Downloads\covid_toy.csv")
df.sample(5)

    age  gender  fever   cough       city has_covid
37   55    Male  100.0    Mild    Kolkata        No
46   19  Female  101.0    Mild     Mumbai        No
22   71  Female   98.0  Strong    Kolkata       Yes
85   16  Female  103.0    Mild  Bangalore       Yes
94   79    Male    NaN  Strong    Kolkata       Yes

In [4]:
df['cough'].value_counts()

cough
Mild      62
Strong    38
Name: count, dtype: int64

In [6]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [8]:
x=df.iloc[:,0:5]
x

    age  gender  fever   cough       city
0    60    Male  103.0    Mild    Kolkata
1    27    Male  100.0    Mild      Delhi
2    42    Male  101.0    Mild      Delhi
3    31  Female   98.0    Mild    Kolkata
4    65  Female  101.0    Mild     Mumbai
..  ...     ...    ...     ...        ...
95   12  Female  104.0    Mild  Bangalore
96   51  Female  101.0  Strong    Kolkata
97   20  Female  101.0    Mild  Bangalore
98    5  Female   98.0  Strong     Mumbai
99   10  Female   98.0  Strong    Kolkata

[100 rows x 5 columns]

In [10]:
y=df.iloc[:,-1]
y

0      No
1     Yes
2      No
3      No
4      No
     ...
95     No
96    Yes
97     No
98     No
99    Yes
Name: has_covid, Length: 100, dtype: object

In [11]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test= train_test_split(x,y,test_size=0.2,random_state=42)

In [13]:
x_train

    age  gender  fever   cough       city
55   81  Female  101.0    Mild     Mumbai
88    5  Female  100.0    Mild    Kolkata
26   19  Female  100.0    Mild    Kolkata
42   27    Male  100.0    Mild      Delhi
69   73  Female  103.0    Mild      Delhi
..  ...     ...    ...     ...        ...
60   24  Female  102.0  Strong  Bangalore
71   75  Female  104.0  Strong      Delhi
14   51    Male  104.0    Mild  Bangalore
92   82  Female  102.0  Strong    Kolkata
51   11  Female  100.0  Strong    Kolkata

[80 rows x 5 columns]

In [14]:
x_test

    age  gender  fever   cough       city
83   17  Female  104.0    Mild    Kolkata
53   83    Male   98.0    Mild      Delhi
70   68  Female  101.0  Strong      Delhi
45   72    Male   99.0    Mild  Bangalore
44   20    Male  102.0  Strong      Delhi
39   50  Female  103.0    Mild    Kolkata
22   71  Female   98.0  Strong    Kolkata
80   14  Female   99.0    Mild     Mumbai
10   75  Female    NaN    Mild      Delhi
0    60    Male  103.0    Mild    Kolkata
18   64  Female   98.0    Mild  Bangalore
30   15    Male  101.0    Mild      Delhi
73   34    Male   98.0  Strong    Kolkata
33   26  Female   98.0    Mild    Kolkata
90   59  Female   99.0  Strong      Delhi
4    65  Female  101.0    Mild     Mumbai
76   80    Male  100.0    Mild  Bangalore
77    8  Female  101.0    Mild    Kolkata
12   25  Female   99.0  Strong    Kolkata
31   83    Male  103.0    Mild    Kolkata

In [15]:
x_test.shape

(20, 5)

# what we need to do in this

add simple imputer on column fever to handle missing values

In [16]:
si=SimpleImputer()
x_train_fever=si.fit_transform(x_train[['fever']])
x_test_fever=si.fit_transform(x_test[['fever']])
x_train_fever.shape

(80, 1)

  add ordinal encoding on column like cough

In [19]:
oe=OrdinalEncoder(categories=[['Mild','Strong']])
x_train_cough=oe.fit_transform(x_train[['cough']])
x_test_cough=oe.fit_transform(x_test[['cough']])
x_train_cough.shape

(80, 1)

add onehot encoding on gender and city

In [23]:
x_train['gender'].value_counts()

gender
Female    47
Male      33
Name: count, dtype: int64

In [24]:
x_train['city'].value_counts()

city
Bangalore    27
Kolkata      23
Delhi        16
Mumbai       14
Name: count, dtype: int64

In [21]:
ohe=OneHotEncoder(drop='first',sparse_output
                  =False)
x_train_gender_city=ohe.fit_transform(x_train[['gender','city']])
x_test_gender_city=ohe.fit_transform(x_test[['gender','city']])
x_train_gender_city.shape

(80, 4)

extract age to conact with tarsformed arrays

In [29]:
x_train_age=x_train.drop(columns=['gender','fever','cough','city']).values
x_test_age=x_test.drop(columns=['gender','fever','cough','city']).values

In [30]:
x_train_age.shape

(80, 1)

conacate all arrays

In [31]:
x_train_transform=np.concatenate((x_train_age,x_train_fever,x_train_gender_city,x_train_cough),axis=1)

In [32]:
x_test_transform=np.concatenate((x_test_age,x_test_fever,x_test_gender_city,x_test_cough),axis=1)

In [33]:
x_train_transform.shape

(80, 7)

# Solution of this problem in just one go

In [34]:
from sklearn.compose import ColumnTransformer

In [38]:
transformer=ColumnTransformer(transformers=[
    ('tnf1',SimpleImputer(),['fever']),
    ('tnf2',OrdinalEncoder(categories=[['Mild','Strong']]),['cough']),
    ('tnf3',OneHotEncoder(sparse_output=False,drop='first'),['gender','city'])
    
],remainder='passthrough')

In [39]:
transformer.fit_transform(x_train).shape

(80, 7)