In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv(r"C:\Users\tyagi\Downloads\cars.csv")
df.sample(5)

           brand  km_driven    fuel         owner  selling_price
6908   Chevrolet      90000  Diesel   Third Owner         145000
4596     Hyundai      80000  Diesel  Second Owner         545000
5492      Maruti     110000  Petrol  Second Owner         280000
1683  Volkswagen      17000  Petrol   First Owner         678000
4877        Tata     120000  Diesel   Third Owner         135000

In [3]:
df['brand'].value_counts()

brand
Maruti           2448
Hyundai          1415
Mahindra          772
Tata              734
Toyota            488
Honda             467
Ford              397
Chevrolet         230
Renault           228
Volkswagen        186
BMW               120
Skoda             105
Nissan             81
Jaguar             71
Volvo              67
Datsun             65
Mercedes-Benz      54
Fiat               47
Audi               40
Lexus              34
Jeep               31
Mitsubishi         14
Land                6
Force               6
Isuzu               5
Ambassador          4
Kia                 4
MG                  3
Daewoo              3
Ashok               1
Opel                1
Peugeot             1
Name: count, dtype: int64

In [4]:
df['brand'].nunique()

32

In [5]:
df['fuel'].value_counts()

fuel
Diesel    4402
Petrol    3631
CNG         57
LPG         38
Name: count, dtype: int64

In [6]:
df['owner'].value_counts()

owner
First Owner             5289
Second Owner            2105
Third Owner              555
Fourth & Above Owner     174
Test Drive Car             5
Name: count, dtype: int64

# one hot encoding using pandas

In [7]:
pd.get_dummies(df,columns=['fuel','owner'])

,brand,km_driven,selling_price,fuel_CNG,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_First Owner,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,False,True,False,False,True,False,False,False,False
1,Skoda,120000,370000,False,True,False,False,False,False,True,False,False
2,Honda,140000,158000,False,False,False,True,False,False,False,False,True
3,Hyundai,127000,225000,False,True,False,False,True,False,False,False,False
4,Maruti,120000,130000,False,False,False,True,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,False,True,True,False,False,False,False
8124,Hyundai,119000,135000,False,True,False,False,False,True,False,False,False
8125,Maruti,120000,382000,False,True,False,False,True,False,False,False,False
8126,Tata,25000,290000,False,True,False,False,True,False,False,False,False
8127,Tata,25000,290000,False,True,False,False,True,False,False,False,False

# K-1 Enconding

In [8]:
pd.get_dummies(df,columns=['fuel','owner'],drop_first=True)

,brand,km_driven,selling_price,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,True,False,False,False,False,False,False
1,Skoda,120000,370000,True,False,False,False,True,False,False
2,Honda,140000,158000,False,False,True,False,False,False,True
3,Hyundai,127000,225000,True,False,False,False,False,False,False
4,Maruti,120000,130000,False,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,True,False,False,False,False
8124,Hyundai,119000,135000,True,False,False,True,False,False,False
8125,Maruti,120000,382000,True,False,False,False,False,False,False
8126,Tata,25000,290000,True,False,False,False,False,False,False
8127,Tata,25000,290000,True,False,False,False,False,False,False

# using skleran

In [34]:
x=df.iloc[:,0:4]
x

        brand  km_driven    fuel                 owner
0      Maruti     145500  Diesel           First Owner
1       Skoda     120000  Diesel          Second Owner
2       Honda     140000  Petrol           Third Owner
3     Hyundai     127000  Diesel           First Owner
4      Maruti     120000  Petrol           First Owner
...       ...        ...     ...                   ...
8123  Hyundai     110000  Petrol           First Owner
8124  Hyundai     119000  Diesel  Fourth & Above Owner
8125   Maruti     120000  Diesel           First Owner
8126     Tata      25000  Diesel           First Owner
8127     Tata      25000  Diesel           First Owner

[8128 rows x 4 columns]

In [35]:
y=df.iloc[:,4:]
y

      selling_price
0            450000
1            370000
2            158000
3            225000
4            130000
...             ...
8123         320000
8124         135000
8125         382000
8126         290000
8127         290000

[8128 rows x 1 columns]

In [36]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.2,random_state=42)

In [37]:
x_train

         brand  km_driven    fuel                 owner
6404    Maruti      80000  Petrol          Second Owner
1555    Maruti     100000  Petrol  Fourth & Above Owner
7349    Maruti     190000  Diesel           First Owner
3190    Maruti      23700  Petrol           First Owner
4566    Toyota     120000  Diesel          Second Owner
...        ...        ...     ...                   ...
5226  Mahindra     120000  Diesel           First Owner
5390    Maruti      80000  Diesel          Second Owner
860    Hyundai      35000  Petrol           First Owner
7603    Maruti      27000  Diesel           First Owner
7270    Maruti      70000  Petrol          Second Owner

[1625 rows x 4 columns]

In [38]:
x_train['owner'].value_counts()

owner
First Owner             1040
Second Owner             434
Third Owner              114
Fourth & Above Owner      37
Name: count, dtype: int64

In [39]:
x_train['fuel'].value_counts()

fuel
Diesel    887
Petrol    726
CNG         6
LPG         6
Name: count, dtype: int64

In [40]:
x_test

        brand  km_driven    fuel         owner
1971    Honda     110000  Petrol   Third Owner
4664     Tata     291977  Diesel   First Owner
5448   Maruti      70000  Diesel   First Owner
3333    Honda     120000  Petrol  Second Owner
2316   Maruti      69000  Diesel  Second Owner
...       ...        ...     ...           ...
5000    Honda     120000  Diesel   First Owner
5853  Hyundai      40000  Petrol   First Owner
1279   Maruti      90000  Diesel   First Owner
7501   Maruti     150000  Diesel   First Owner
7959  Hyundai      65000  Petrol   First Owner

[6503 rows x 4 columns]

In [41]:
x_test['owner'].value_counts()

owner
First Owner             4249
Second Owner            1671
Third Owner              441
Fourth & Above Owner     137
Test Drive Car             5
Name: count, dtype: int64

In [42]:
x_test['fuel'].value_counts()

fuel
Diesel    3515
Petrol    2905
CNG         51
LPG         32
Name: count, dtype: int64

In [47]:
from sklearn.preprocessing import OneHotEncoder
ohe=OneHotEncoder(drop='first',sparse_output=False,handle_unknown='ignore')

In [48]:

x_train_new = ohe.fit_transform(x_train[['fuel','owner']])

In [49]:
x_train_new

array([[0., 0., 1., 0., 1., 0.],
       [0., 0., 1., 1., 0., 0.],
       [1., 0., 0., 0., 0., 0.],
       ...,
       [0., 0., 1., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 1., 0.]])

In [50]:
x_test_new=ohe.transform(x_test[['fuel','owner']])

C:\Users\tyagi\AppData\Roaming\Python\Python313\site-packages\sklearn\preprocessing\_encoders.py:246: UserWarning: Found unknown categories in columns [1] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

In [51]:
x_test_new

array([[0., 0., 1., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0.],
       ...,
       [1., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.]])

In [52]:
x_train_new.shape

(1625, 6)

In [53]:
x_test_new.shape

(6503, 6)

In [54]:
np.hstack((x_train[['brand','km_driven']].values,x_train_new))

array([['Maruti', 80000, 0.0, ..., 0.0, 1.0, 0.0],
       ['Maruti', 100000, 0.0, ..., 1.0, 0.0, 0.0],
       ['Maruti', 190000, 1.0, ..., 0.0, 0.0, 0.0],
       ...,
       ['Hyundai', 35000, 0.0, ..., 0.0, 0.0, 0.0],
       ['Maruti', 27000, 1.0, ..., 0.0, 0.0, 0.0],
       ['Maruti', 70000, 0.0, ..., 0.0, 1.0, 0.0]], dtype=object)

# One Hot Encoding with top categories

In [64]:
counts=df['brand'].value_counts()

In [59]:
df['brand'].nunique()
threshold=100

In [62]:
repl=counts[counts <= threshold].index

In [63]:
pd.get_dummies(df['brand'].replace(repl,'Others'))

,BMW,Chevrolet,Ford,Honda,Hyundai,Mahindra,Maruti,Others,Renault,Skoda,Tata,Toyota,Volkswagen
0,False,False,False,False,False,False,True,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,True,False,False,False
2,False,False,False,True,False,False,False,False,False,False,False,False,False
3,False,False,False,False,True,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,True,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8123,False,False,False,False,True,False,False,False,False,False,False,False,False
8124,False,False,False,False,True,False,False,False,False,False,False,False,False
8125,False,False,False,False,False,False,True,False,False,False,False,False,False
8126,False,False,False,False,False,False,False,False,False,False,True,False,False
8127,False,False,False,False,False,False,False,False,False,False,True,False,False