# ordinal encoding

In [2]:
import numpy as np
import pandas as pd

In [4]:
df=pd.read_csv(r"C:\Users\tyagi\Downloads\customer.csv")
df.sample(5)

    age  gender review education purchased
14   15    Male   Poor        PG       Yes
1    68  Female   Poor        UG        No
18   19    Male   Good    School        No
25   57  Female   Good    School        No
36   34  Female   Good        UG       Yes

In [6]:
df=df.iloc[:,2:]

In [7]:
df.head(5)

    review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [31]:
x=df[['review','education']]
y=df[['purchased']]
x.head(5)

    review education
0  Average    School
1     Poor        UG
2     Good        PG
3     Good        PG
4  Average        UG

In [32]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.2,random_state=42)
x_train.shape , x_test.shape

((10, 2), (40, 2))

In [33]:
x_train

     review education
10     Good        UG
22     Poor        PG
18     Good    School
49     Good        UG
20  Average    School
7      Poor    School
42     Good        PG
14     Poor        PG
28     Poor    School
38     Good    School

In [25]:
from sklearn.preprocessing  import OrdinalEncoder

In [26]:
oe=OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])

In [27]:
oe.fit(x_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [28]:
x_train=oe.transform(x_train)

In [29]:
x_train

array([[2., 1.],
       [0., 2.],
       [2., 0.],
       [2., 1.],
       [1., 0.],
       [0., 0.],
       [2., 2.],
       [0., 2.],
       [0., 0.],
       [2., 0.]])

In [34]:
x_test=oe.transform(x_test)

In [35]:
x_test

array([[1., 0.],
       [0., 2.],
       [1., 1.],
       [0., 2.],
       [0., 1.],
       [2., 1.],
       [0., 2.],
       [2., 0.],
       [1., 1.],
       [0., 2.],
       [0., 0.],
       [1., 1.],
       [1., 2.],
       [1., 1.],
       [2., 2.],
       [2., 0.],
       [2., 2.],
       [0., 2.],
       [2., 2.],
       [0., 1.],
       [2., 1.],
       [0., 1.],
       [1., 2.],
       [1., 0.],
       [0., 0.],
       [1., 0.],
       [1., 1.],
       [0., 2.],
       [2., 2.],
       [1., 0.],
       [1., 1.],
       [2., 1.],
       [2., 1.],
       [0., 1.],
       [1., 2.],
       [2., 2.],
       [0., 2.],
       [0., 0.],
       [2., 0.],
       [2., 0.]])

In [40]:
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

# Label Enconding 
     use to encode only output values means y data

In [36]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

In [37]:
le.fit(y_train)

C:\Users\tyagi\AppData\Roaming\Python\Python313\site-packages\sklearn\preprocessing\_label.py:93: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

LabelEncoder()

In [39]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [41]:
y_train=le.transform(y_train)
y_test=le.transform(y_test)

C:\Users\tyagi\AppData\Roaming\Python\Python313\site-packages\sklearn\preprocessing\_label.py:129: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)
C:\Users\tyagi\AppData\Roaming\Python\Python313\site-packages\sklearn\preprocessing\_label.py:129: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

In [42]:
y_train

array([1, 1, 0, 0, 1, 1, 1, 1, 0, 0])

In [43]:
y_test

array([0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1,
       1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0])